version: "3.9"
services:
  postgres-server:
    container_name: postgres-server
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=wynn_otp
    volumes:
      - "database_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - dev-network
networks:
  dev-network:
    driver: bridge
volumes:
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local
  database_data:
    driver: local

